# Sorry guys credit card got hacked I need to reset it lol for now this will be blank



# Support me by using the funding links below
# Developed and Maintained by DaCuteRaccoon

custom: ['https://example.com/donate.html','https://example.com/paypal.aspx']

# Your donation means a lot to me to continue the development of open source project like this.
